AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stack Principal - Sistema de Scheduling de Órdenes de Compra - Acme Inc.'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Ambiente de despliegue

Resources:
  # ==================== VPC y NETWORKING ====================
  
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: AcmeSchedulingVPC

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: AcmePrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: AcmePrivateSubnet2

  # Security Group para Lambdas
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para Lambdas
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AcmeLambdaSG

  # VPC Endpoint para DynamoDB
  DynamoDBVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable

  # Route Table para subredes privadas
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: AcmePrivateRouteTable

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  # VPC Endpoint para CloudWatch Logs
  CloudWatchLogsVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup

  # ==================== KMS ====================
  
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Clave KMS para cifrado de DynamoDB y variables de entorno
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow DynamoDB to use the key
            Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action:
              - 'kms:Decrypt'
              - 'kms:DescribeKey'
              - 'kms:CreateGrant'
            Resource: '*'
          - Sid: Allow Lambda to use the key
            Effect: Allow
            Principal:
              AWS:
                - !ImportValue AcmeSchedulerManagerRoleArn
                - !ImportValue AcmeOrderExecutorRoleArn
            Action:
              - 'kms:Decrypt'
              - 'kms:Encrypt'
              - 'kms:GenerateDataKey'
              - 'kms:DescribeKey'
            Resource: '*'

  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/acme-scheduling-key
      TargetKeyId: !Ref KMSKey

  # ==================== DYNAMODB ====================
  
  PurchaseOrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PurchaseOrdersTable
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKey
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ScheduleDefinitionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ScheduleDefinitionsTable
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKey
      AttributeDefinitions:
        - AttributeName: scheduleId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: scheduleId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ==================== COGNITO ====================
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AcmeSchedulingUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AcmeSchedulingAppClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  # ==================== LAMBDA FUNCTIONS ====================
  
  SchedulerManagerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: acme-scheduler-manager
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !ImportValue AcmeSchedulerManagerRoleArn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder'}
      Environment:
        Variables:
          SCHEDULE_TABLE_NAME: !Ref ScheduleDefinitionsTable
          ORDER_EXECUTOR_ARN: !GetAtt OrderExecutorFunction.Arn
          SCHEDULER_ROLE_ARN: !ImportValue AcmeEventBridgeSchedulerRoleArn
          KMS_KEY_ID: !Ref KMSKey
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Timeout: 30
      MemorySize: 256
      KmsKeyArn: !GetAtt KMSKey.Arn

  OrderExecutorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: acme-order-executor
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !ImportValue AcmeOrderExecutorRoleArn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder'}
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref PurchaseOrdersTable
          SCHEDULE_TABLE_NAME: !Ref ScheduleDefinitionsTable
          KMS_KEY_ID: !Ref KMSKey
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Timeout: 30
      MemorySize: 256
      KmsKeyArn: !GetAtt KMSKey.Arn

  # ==================== API GATEWAY ====================
  
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: AcmeSchedulingAPI
      Description: API para gestión de schedules y órdenes de compra
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Authorizer de Cognito
  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref RestApi
      ProviderARNs:
        - !GetAtt UserPool.Arn

  # Recursos y Métodos
  ScheduleResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: schedule

  SchedulesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: schedules

  ScheduleIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref ScheduleResource
      PathPart: '{scheduleId}'

  OrdersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: orders

  # POST /schedule
  PostScheduleMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ScheduleResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SchedulerManagerFunction.Arn}/invocations'

  # GET /schedules
  GetSchedulesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref SchedulesResource
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SchedulerManagerFunction.Arn}/invocations'

  # DELETE /schedule/{scheduleId}
  DeleteScheduleMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ScheduleIdResource
      HttpMethod: DELETE
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SchedulerManagerFunction.Arn}/invocations'

  # GET /orders
  GetOrdersMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref OrdersResource
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SchedulerManagerFunction.Arn}/invocations'

  # Permisos para API Gateway invocar Lambdas
  SchedulerManagerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SchedulerManagerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*'

  # Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostScheduleMethod
      - GetSchedulesMethod
      - DeleteScheduleMethod
      - GetOrdersMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: !Ref Environment

Outputs:
  ApiEndpoint:
    Description: URL del API Gateway
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: AcmeSchedulingApiEndpoint

  UserPoolId:
    Description: ID del User Pool de Cognito
    Value: !Ref UserPool
    Export:
      Name: AcmeUserPoolId

  UserPoolClientId:
    Description: ID del App Client de Cognito
    Value: !Ref UserPoolClient
    Export:
      Name: AcmeUserPoolClientId

  KMSKeyId:
    Description: ID de la clave KMS
    Value: !Ref KMSKey
    Export:
      Name: AcmeKMSKeyId

  PurchaseOrdersTableName:
    Description: Nombre de la tabla de órdenes
    Value: !Ref PurchaseOrdersTable

  ScheduleDefinitionsTableName:
    Description: Nombre de la tabla de definiciones de schedules
    Value: !Ref ScheduleDefinitionsTable
