AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Table for Cartoon Rekognition - Analysis results storage with encryption, point-in-time recovery, and GSI'

Parameters:
  Environment:
    Type: String
    Description: Environment name (sandbox, preprod, prod)
    AllowedValues:
      - sandbox
      - preprod
      - prod
    Default: sandbox

  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: cartoon-rekognition

  KMSStackName:
    Type: String
    Description: Name of the KMS CloudFormation stack
    Default: cartoon-rekognition-kms

  EnableGSI:
    Type: String
    Description: Enable Global Secondary Index for CharacterName-Timestamp queries
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
          - ProjectName
      - Label:
          default: Stack Dependencies
        Parameters:
          - KMSStackName
      - Label:
          default: Table Configuration
        Parameters:
          - EnableGSI

Conditions:
  CreateGSI: !Equals [!Ref EnableGSI, 'true']

Resources:
  # DynamoDB Table for Cartoon Analysis Results
  CartoonAnalysisResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-analysis-results-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ImageId
          AttributeType: S
        - AttributeName: CharacterName
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: ImageId
          KeyType: HASH
      GlobalSecondaryIndexes:
        !If
          - CreateGSI
          - - IndexName: CharacterName-Timestamp-index
              KeySchema:
                - AttributeName: CharacterName
                  KeyType: HASH
                - AttributeName: Timestamp
                  KeyType: RANGE
              Projection:
                ProjectionType: ALL
          - !Ref AWS::NoValue
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId:
          Fn::ImportValue: !Sub '${KMSStackName}-DynamoDB-KeyId'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-analysis-results-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Analysis Results Storage

Outputs:
  TableName:
    Description: Name of the DynamoDB table for cartoon analysis results
    Value: !Ref CartoonAnalysisResultsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'

  TableArn:
    Description: ARN of the DynamoDB table for cartoon analysis results
    Value: !GetAtt CartoonAnalysisResultsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'

  TableStreamArn:
    Description: Stream ARN of the DynamoDB table
    Value: !GetAtt CartoonAnalysisResultsTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-TableStreamArn'

  GSIName:
    Condition: CreateGSI
    Description: Name of the Global Secondary Index for CharacterName-Timestamp queries
    Value: CharacterName-Timestamp-index
    Export:
      Name: !Sub '${AWS::StackName}-GSIName'
