AWSTemplateFormatVersion: '2010-09-09'
Description: 'Acme Image Handler - Serverless Architecture Base'

Parameters:
  EnvironmentName:
    Type: String
    Default: sandbox
    AllowedValues: [sandbox, pre-prod, prod]
  
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID para las Lambdas
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Primera subred privada
  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Segunda subred privada
  
  KMSKeyArn:
    Type: String
    Description: ARN de la KMS key para cifrado

Resources:
  # ==================== S3 BUCKETS ====================
  
  RawImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'acme-gadgets-raw-${AWS::AccountId}-${EnvironmentName}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKeyArn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ProcessedImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'acme-gadgets-processed-${AWS::AccountId}-${EnvironmentName}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKeyArn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ==================== DYNAMODB ====================
  
  GadgetImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'GadgetImages-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        Enabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKeyArn
      AttributeDefinitions:
        - AttributeName: gadgetId
          AttributeType: S
        - AttributeName: imageId
          AttributeType: S
      KeySchema:
        - AttributeName: gadgetId
          KeyType: HASH
        - AttributeName: imageId
          KeyType: RANGE

  # ==================== IAM ROLES ====================
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'acme-image-handler-lambda-role-${EnvironmentName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt RawImagesBucket.Arn
                  - !Sub '${RawImagesBucket.Arn}/*'
                  - !GetAtt ProcessedImagesBucket.Arn
                  - !Sub '${ProcessedImagesBucket.Arn}/*'
        
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt GadgetImagesTable.Arn
        
        - PolicyName: KMSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !Ref KMSKeyArn
        
        - PolicyName: LogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  # ==================== LAMBDA FUNCTIONS ====================
  
  ImageProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'acme-image-processor-${EnvironmentName}'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Environment:
        Variables:
          PROCESSED_BUCKET: !Ref ProcessedImagesBucket
          DYNAMODB_TABLE: !Ref GadgetImagesTable
      Code:
        ZipFile: |
          # Placeholder - se reemplaza en CI/CD
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('OK')}

  ApiHandlerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'acme-api-handler-${EnvironmentName}'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Environment:
        Variables:
          PROCESSED_BUCKET: !Ref ProcessedImagesBucket
          RAW_BUCKET: !Ref RawImagesBucket
          DYNAMODB_TABLE: !Ref GadgetImagesTable
      Code:
        ZipFile: |
          # Placeholder
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('OK')}

  # S3 Trigger para procesador de imágenes
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageProcessorLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt RawImagesBucket.Arn

  RawImagesBucketNotification:
    Type: AWS::S3::Bucket
    DependsOn: S3InvokeLambdaPermission
    Properties:
      BucketName: !Ref RawImagesBucket
      NotificationConfiguration:
        LambdaFunctionConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ImageProcessorLambda.Arn

  # ==================== SECURITY GROUP ====================
  
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para Lambdas
      VpcId: !Ref VPCId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS saliente

Outputs:
  RawBucketName:
    Value: !Ref RawImagesBucket
    Description: Nombre del bucket RAW
  
  ProcessedBucketName:
    Value: !Ref ProcessedImagesBucket
    Description: Nombre del bucket PROCESSED
  
  DynamoDBTableName:
    Value: !Ref GadgetImagesTable
    Description: Nombre de la tabla DynamoDB
  
  ImageProcessorLambdaArn:
    Value: !GetAtt ImageProcessorLambda.Arn
    Description: ARN de la Lambda procesadora
  
  ApiHandlerLambdaArn:
    Value: !GetAtt ApiHandlerLambda.Arn
    Description: ARN de la Lambda del API
