AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI/CD Pipeline para Acme Image Handler - Célula 3'

Parameters:
  GitHubRepo:
    Type: String
    Description: Nombre del repositorio GitHub
    Default: acme-image-handler
  
  GitHubOwner:
    Type: String
    Description: Owner del repositorio GitHub
  
  GitHubBranch:
    Type: String
    Description: Branch a monitorear
    Default: main
  
  GitHubToken:
    Type: String
    Description: GitHub Personal Access Token
    NoEcho: true
  
  SandboxAccountId:
    Type: String
    Description: Account ID para Sandbox
  
  PreProdAccountId:
    Type: String
    Description: Account ID para Pre-Producción
  
  ProdAccountId:
    Type: String
    Description: Account ID para Producción

Resources:
  # ==================== S3 BUCKET PARA ARTEFACTOS ====================
  
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'acme-pipeline-artifacts-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30
  
  # ==================== IAM ROLES ====================
  
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: acme-codepipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      Policies:
        - PolicyName: PipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub '${ArtifactBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: '*'
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
  
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: acme-codebuild-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
      Policies:
        - PolicyName: BuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub '${ArtifactBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource: '*'
  
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: acme-cloudformation-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  
  # ==================== CODEBUILD PROJECTS ====================
  
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: acme-image-handler-build
      Description: Build project para Acme Image Handler
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref ArtifactBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 15
  
  # ==================== CODEPIPELINE ====================
  
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: acme-image-handler-pipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        # Stage 1: Source
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceOutput
        
        # Stage 2: Build
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
        
        # Stage 3: Deploy to Sandbox
        - Name: DeployToSandbox
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: acme-image-handler-sandbox
                TemplatePath: BuildOutput::build/cloudformation-base.yaml
                TemplateConfiguration: BuildOutput::pipeline/parameters-sandbox.json
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CloudFormationRole.Arn
              InputArtifacts:
                - Name: BuildOutput
        
        # Stage 4: Deploy to Pre-Prod (Manual Approval)
        - Name: DeployToPreProd
          Actions:
            - Name: ApprovalAction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: 'Aprobar despliegue a Pre-Producción'
            
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: acme-image-handler-pre-prod
                TemplatePath: BuildOutput::build/cloudformation-base.yaml
                TemplateConfiguration: BuildOutput::pipeline/parameters-pre-prod.json
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CloudFormationRole.Arn
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 2
        
        # Stage 5: Deploy to Production (Manual Approval)
        - Name: DeployToProduction
          Actions:
            - Name: ApprovalAction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: 'Aprobar despliegue a Producción'
            
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: acme-image-handler-prod
                TemplatePath: BuildOutput::build/cloudformation-base.yaml
                TemplateConfiguration: BuildOutput::pipeline/parameters-prod.json
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CloudFormationRole.Arn
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 2

Outputs:
  PipelineName:
    Value: !Ref Pipeline
    Description: Nombre del pipeline
  
  PipelineUrl:
    Value: !Sub 'https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${Pipeline}/view'
    Description: URL del pipeline en la consola
  
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Description: Bucket de artefactos
